//
//  CarbonEmmisionStruct.swift
//  Swift International Challenge P1
//
//  Created by Neel Arora on 9/20/25.
//

import Foundation
struct CarbonEmissionStruct: Identifiable{
    var id: UUID = UUID()
    var countryName: String
    var avgAmountOfCarbonEmissions: Double
}
// Metric Tons of carbon emission
let countryCarbonEmission: [CarbonEmissionStruct] = [
    CarbonEmissionStruct(countryName: "United States", avgAmountOfCarbonEmissions: 14.21),
    CarbonEmissionStruct(countryName: "China", avgAmountOfCarbonEmissions: 8.89),
    CarbonEmissionStruct(countryName: "India", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Russia", avgAmountOfCarbonEmissions: 13.11),
    CarbonEmissionStruct(countryName: "Japan", avgAmountOfCarbonEmissions: 8.66),
    CarbonEmissionStruct(countryName: "Iran", avgAmountOfCarbonEmissions: 7.67),
    CarbonEmissionStruct(countryName: "Indonesia", avgAmountOfCarbonEmissions: 2.48),
    CarbonEmissionStruct(countryName: "Saudi Arabia", avgAmountOfCarbonEmissions: 18.89),
    CarbonEmissionStruct(countryName: "Germany", avgAmountOfCarbonEmissions: 8.01),
    CarbonEmissionStruct(countryName: "Canada", avgAmountOfCarbonEmissions: 14.99),
    CarbonEmissionStruct(countryName: "South Korea", avgAmountOfCarbonEmissions: 12.27),
    CarbonEmissionStruct(countryName: "Mexico", avgAmountOfCarbonEmissions: 3.79),
    CarbonEmissionStruct(countryName: "Brazil", avgAmountOfCarbonEmissions: 2.22),
    CarbonEmissionStruct(countryName: "Turkey", avgAmountOfCarbonEmissions: 5.53),
    CarbonEmissionStruct(countryName: "Australia", avgAmountOfCarbonEmissions: 15.01),
    CarbonEmissionStruct(countryName: "United Kingdom", avgAmountOfCarbonEmissions: 5.00),
    CarbonEmissionStruct(countryName: "Vietnam", avgAmountOfCarbonEmissions: 3.29),
    CarbonEmissionStruct(countryName: "Italy", avgAmountOfCarbonEmissions: 5.42),
    CarbonEmissionStruct(countryName: "Poland", avgAmountOfCarbonEmissions: 8.39),
    CarbonEmissionStruct(countryName: "France", avgAmountOfCarbonEmissions: 4.76),
    CarbonEmissionStruct(countryName: "Taiwan", avgAmountOfCarbonEmissions: 3.47),
    CarbonEmissionStruct(countryName: "Thailand", avgAmountOfCarbonEmissions: 3.29),
    CarbonEmissionStruct(countryName: "Egypt", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Kazakhstan", avgAmountOfCarbonEmissions: 7.23),
    CarbonEmissionStruct(countryName: "Spain", avgAmountOfCarbonEmissions: 4.88),
    CarbonEmissionStruct(countryName: "United Arab Emirates", avgAmountOfCarbonEmissions: 18.89),
    CarbonEmissionStruct(countryName: "Pakistan", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Iraq", avgAmountOfCarbonEmissions: 5.53),
    CarbonEmissionStruct(countryName: "Argentina", avgAmountOfCarbonEmissions: 3.29),
    CarbonEmissionStruct(countryName: "Algeria", avgAmountOfCarbonEmissions: 3.29),
    CarbonEmissionStruct(countryName: "Philippines", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Uzbekistan", avgAmountOfCarbonEmissions: 3.47),
    CarbonEmissionStruct(countryName: "Ukraine", avgAmountOfCarbonEmissions: 3.29),
    CarbonEmissionStruct(countryName: "Nigeria", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Qatar", avgAmountOfCarbonEmissions: 18.89),
    CarbonEmissionStruct(countryName: "Bangladesh", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Netherlands", avgAmountOfCarbonEmissions: 4.88),
    CarbonEmissionStruct(countryName: "Kuwait", avgAmountOfCarbonEmissions: 18.89),
    CarbonEmissionStruct(countryName: "Colombia", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Oman", avgAmountOfCarbonEmissions: 7.23),
    CarbonEmissionStruct(countryName: "Czech Republic", avgAmountOfCarbonEmissions: 5.53),
    CarbonEmissionStruct(countryName: "Venezuela", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Belgium", avgAmountOfCarbonEmissions: 4.88),
    CarbonEmissionStruct(countryName: "Chile", avgAmountOfCarbonEmissions: 3.29),
    CarbonEmissionStruct(countryName: "Romania", avgAmountOfCarbonEmissions: 3.47),
    CarbonEmissionStruct(countryName: "Morocco", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Turkmenistan", avgAmountOfCarbonEmissions: 3.47),
    CarbonEmissionStruct(countryName: "North Korea", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Libya", avgAmountOfCarbonEmissions: 3.47),
    CarbonEmissionStruct(countryName: "Israel", avgAmountOfCarbonEmissions: 3.47),
    CarbonEmissionStruct(countryName: "Austria", avgAmountOfCarbonEmissions: 5.53),
    CarbonEmissionStruct(countryName: "Peru", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Singapore", avgAmountOfCarbonEmissions: 3.47),
    CarbonEmissionStruct(countryName: "Serbia", avgAmountOfCarbonEmissions: 3.29),
    CarbonEmissionStruct(countryName: "Belarus", avgAmountOfCarbonEmissions: 3.47),
    CarbonEmissionStruct(countryName: "Greece", avgAmountOfCarbonEmissions: 3.47),
    CarbonEmissionStruct(countryName: "Ecuador", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Norway", avgAmountOfCarbonEmissions: 5.53),
    CarbonEmissionStruct(countryName: "Hungary", avgAmountOfCarbonEmissions: 3.47),
    CarbonEmissionStruct(countryName: "Azerbaijan", avgAmountOfCarbonEmissions: 3.29),
    CarbonEmissionStruct(countryName: "Bulgaria", avgAmountOfCarbonEmissions: 3.29),
    CarbonEmissionStruct(countryName: "Bahrain", avgAmountOfCarbonEmissions: 18.89),
    CarbonEmissionStruct(countryName: "Portugal", avgAmountOfCarbonEmissions: 4.88),
    CarbonEmissionStruct(countryName: "New Zealand", avgAmountOfCarbonEmissions: 6.36),
    CarbonEmissionStruct(countryName: "Sweden", avgAmountOfCarbonEmissions: 4.88),
    CarbonEmissionStruct(countryName: "Slovakia", avgAmountOfCarbonEmissions: 5.53),
    CarbonEmissionStruct(countryName: "Hong Kong", avgAmountOfCarbonEmissions: 3.29),
    CarbonEmissionStruct(countryName: "Switzerland", avgAmountOfCarbonEmissions: 4.88),
    CarbonEmissionStruct(countryName: "Myanmar", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Ireland", avgAmountOfCarbonEmissions: 5.53),
    CarbonEmissionStruct(countryName: "Finland", avgAmountOfCarbonEmissions: 5.53),
    CarbonEmissionStruct(countryName: "Tunisia", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Dominican Republic", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Angola", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Mongolia", avgAmountOfCarbonEmissions: 6.36),
    CarbonEmissionStruct(countryName: "Trinidad and Tobago", avgAmountOfCarbonEmissions: 18.89),
    CarbonEmissionStruct(countryName: "Denmark", avgAmountOfCarbonEmissions: 5.53),
    CarbonEmissionStruct(countryName: "Laos", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Syria", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Ghana", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Bolivia", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Jordan", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Cuba", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Bosnia and Herzegovina", avgAmountOfCarbonEmissions: 5.53),
    CarbonEmissionStruct(countryName: "Kenya", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Guatemala", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Sudan", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Sri Lanka", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Tanzania", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Cambodia", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Nepal", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Croatia", avgAmountOfCarbonEmissions: 5.53),
    CarbonEmissionStruct(countryName: "Lebanon", avgAmountOfCarbonEmissions: 3.47),
    CarbonEmissionStruct(countryName: "Ethiopia", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Panama", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Ivory Coast", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Puerto Rico", avgAmountOfCarbonEmissions: 3.29),
    CarbonEmissionStruct(countryName: "Lithuania", avgAmountOfCarbonEmissions: 4.88),
    CarbonEmissionStruct(countryName: "Georgia", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Slovenia", avgAmountOfCarbonEmissions: 5.53),
    CarbonEmissionStruct(countryName: "Senegal", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Zimbabwe", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Estonia", avgAmountOfCarbonEmissions: 7.23),
    CarbonEmissionStruct(countryName: "Honduras", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Yemen", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Cameroon", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Kyrgyzstan", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Moldova", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Mozambique", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Brunei", avgAmountOfCarbonEmissions: 18.89),
    CarbonEmissionStruct(countryName: "Tajikistan", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Uruguay", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "North Macedonia", avgAmountOfCarbonEmissions: 3.29),
    CarbonEmissionStruct(countryName: "Afghanistan", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Costa Rica", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "El Salvador", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Paraguay", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Zambia", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Armenia", avgAmountOfCarbonEmissions: 2.91),
    CarbonEmissionStruct(countryName: "Botswana", avgAmountOfCarbonEmissions: 3.29),
    CarbonEmissionStruct(countryName: "Congo", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Uganda", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Cyprus", avgAmountOfCarbonEmissions: 5.53),
    CarbonEmissionStruct(countryName: "Luxembourg", avgAmountOfCarbonEmissions: 14.21),
    CarbonEmissionStruct(countryName: "Jamaica", avgAmountOfCarbonEmissions: 1.89),
    CarbonEmissionStruct(countryName: "Mali", avgAmountOfCarbonEmissions: 1.89)
]

