// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "EcoHelp",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "EcoHelp",
            targets: ["AppModule"],
            bundleIdentifier: "co.neelStanford.SwiftChallengePt4",
            teamIdentifier: "65C2DBC547",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            additionalInfoPlistContentFilePath: "Info.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("3D Models")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)